const MAINNET_USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const DEVNET_USDC = "Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr";

const USDC = DEVNET_USDC;

const DECIMALS = 10 ** 6;

const BASE_API_URL = process.env.NEXT_PUBLIC_BASE_URL + "/api";

export { MAINNET_USDC, DEVNET_USDC, USDC, BASE_API_URL, DECIMALS };
